#!/usr/bin/env bash

set -eu

search_configs() {
    local global_conf="/etc/devpod/config.sh"
    if [[ -f "$global_conf" ]]; then
        export DEVPOD_GLOBAL_CONF="$global_conf"
    fi

    local user_conf="$HOME/.config/devpod/config.sh"
    if [[ -f "$user_conf" ]]; then
        export DEVPOD_USER_CONF="$user_conf"
    fi

    local git_root
    if git_root="$(git rev-parse --show-toplevel 2>/dev/null)"; then
        local git_root_conf="$git_root/.devpod.sh"
        if [[ -f "$git_root_conf" ]]; then
            export DEVPOD_GIT_ROOT_CONF="$git_root_conf"
        fi
    fi

    local pwd_conf="$PWD/.devpod.sh"
    if [[ -f "$pwd_conf" ]]; then
        export DEVPOD_PWD_CONF="$pwd_conf"
    fi
}

search_and_source_config() {
    search_configs

    if [[ -n "${DEVPOD_PWD_CONF-}" ]]; then
        # shellcheck source=/dev/null
        source "$DEVPOD_PWD_CONF"
        return 0
    fi
    if [[ -n "${DEVPOD_GIT_ROOT_CONF-}" ]]; then
        # shellcheck source=/dev/null
        source "$DEVPOD_GIT_ROOT_CONF"
        return 0
    fi
    if [[ -n "${DEVPOD_USER_CONF-}" ]]; then
        # shellcheck source=/dev/null
        source "$DEVPOD_USER_CONF"
        return 0
    fi
    if [[ -n "${DEVPOD_GLOBAL_CONF-}" ]]; then
        # shellcheck source=/dev/null
        source "$DEVPOD_GLOBAL_CONF"
        return 0
    fi
}

show_help() {
    echo "usage: $(basename "$BASH_ARGV0")"
}

cmd_pull() {
    local distro="debian"

    while getopts "hd:" opt; do
        case "$opt" in
        h)
            show_help
            exit 1
            ;;
        d)
            distro="$OPTARG"
            ;;
        *)
            show_help
            exit 1
            ;;
        esac
    done

    # TODO: Add more containers upstream.
    case "$distro" in
    debian)
        podman pull "ghcr.io/rumpelsepp/devpod:master"
        ;;
    *)
        show_help
        exit 1
        ;;
    esac
}

cmd_run() {
    configured_args=()
    CONTAINER_HOME="/home/dev"

    search_and_source_config

    local container="ghcr.io/rumpelsepp/devpod:master"
    local allow_gui="0"
    local allow_ssh="0"

    while getopts "hgsc:" opt; do
        case "$opt" in
        c)
            container="$OPTARG"
            ;;
        g)
            allow_gui="1"
            ;;
        s)
            allow_ssh="1"
            ;;
        h)
            show_help
            exit 0
            ;;
        *)
            show_help
            exit 1
            ;;
        esac
    done

    shift $((OPTIND - 1))

    local cmd
    if [[ "$#" == 0 ]]; then
        if [[ -v SHELL ]]; then
            cmd+=("$SHELL")
        else
            show_help
            exit 1
        fi
    else
        cmd=("/bin/sh" "-c" "$*")
    fi

    local args
    args=(
        --rm
        --interactive
        --tty
        --workdir "$CONTAINER_HOME/PWD/$(basename "$PWD")"
        --volume "$PWD:$CONTAINER_HOME/PWD/$(basename "$PWD")"
        --volume "$XDG_RUNTIME_DIR:$XDG_RUNTIME_DIR"
        --tmpfs "/tmp:rw,size=787448k,mode=1777"  # TODO: calculate size somehow?
        --log-driver none
        --hostname "devpod"
        --group-add keep-groups
        --userns keep-id
    )

    if [[ -v COLORTERM ]]; then
        args+=(--env "COLORTERM=$COLORTERM")
    fi

    if [[ -v TERM_PROGRAM ]]; then
        args+=(--env "TERM_PROGRAM=$TERM_PROGRAM")
    fi

    if [[ -v SHELL ]]; then
        args+=(--env "SHELL=$SHELL")
    fi

    if ((allow_ssh)); then
        args+=(
            --env "SSH_AUTH_SOCK=$SSH_AUTH_SOCK"
            --volume "$SSH_AUTH_SOCK:$SSH_AUTH_SOCK"
            --volume "$HOME/.ssh:$CONTAINER_HOME/.ssh:O"
        )
    fi

    if ((allow_gui)); then
        args+=(
            # --env "XDG_DATA_DIRS=$XDG_DATA_DIRS"  # TODO: not mounted
            --env "XDG_SESSION_CLASS=$XDG_SESSION_CLASS"
            --env "XDG_RUNTIME_DIR=$XDG_RUNTIME_DIR"
            --env "XDG_SESSION_DESKTOP=$XDG_SESSION_DESKTOP"
            --env "XDG_CURRENT_DESKTOP=$XDG_CURRENT_DESKTOP"
            --env "XDG_MENU_PREFIX=$XDG_MENU_PREFIX"
            --env "XDG_SESSION_TYPE=$XDG_SESSION_TYPE"
            --env "WAYLAND_DISPLAY=$WAYLAND_DISPLAY"
            --env "DBUS_SESSION_BUS_ADDRESS=$DBUS_SESSION_BUS_ADDRESS"
            --device "/dev/dri"
        )
    fi

    podman run "${args[@]}" "${configured_args[@]}" "$container" "${cmd[@]}"
}

main() {
    if [[ "$#" == 0 ]]; then
        show_help
        exit 1
    fi

    case "$1" in
    pull)
        shift
        cmd_pull "$@"
        ;;
    run)
        shift
        cmd_run "$@"
        ;;
    *)
        show_help
        exit 1
        ;;
    esac
}

main "$@"
